### ISSUE TITLE
bank2ynab: date format for Personal Capital?

### ISSUE THREAD

**Issue by torbengb** [mgrecar/pc_to_ynab#1]
A year ago you submitted your bank's CSV format to the "bank2ynab" project. We have expanded the functionality a lot in the meantime, but there is a detail I need to ask from you:

Can you please tell me the date format in Personal Capital's CSV export? Is it day.month.year or year/month/day or something else? I would like to know the sequence and also the separator character please.

Greetings from Austria,
Ben

**Comment by mgrecar** [comment]
Hi Ben,

Unfortunately, I'm not sure what it is.  I haven't used Personal Capital in years, and the code here is just letting `Date.parse` figure out the formatting on the input side.  My best guess would be `mm/dd/YY` or `mm-dd-yyyy`, but that's not founded in science, just my gut feeling.  I'm _pretty_ sure the month appears before the day though, as that's the standard practice for Americans, I know other parts of the world tend to put day before month.

Cheers,
Matt
